id: A909FF784
title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
type: translation
pechas:
- IE54764F9
- I6BAA5D5E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:08:38.945533
  last_modified_at: 2023-01-04 13:08:38.945540
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IE54764F9/8A41: 2A1F
  I6BAA5D5E/5AAB: 2A1F
